name: next_step
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  curved_navigation_bar: ^1.0.6
  table_calendar: ^3.0.0
  percent_indicator: ^4.0.0
  model_viewer_plus: ^1.9.1
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/APPSAARTHI.jpeg"
  adaptive_background_color: "#ffffff"
  adaptive_icon_foreground: "assets/images/APPSAARTHI.jpeg"
  adaptive_icon_background: "#ffffff"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/models/ar_geometry_model.glb
    - assets/models/ar_chemistry_model.glb
    - assets/models/ar_monuments_model.glb

     
    # This ensures that both your assets and images are included

  # To add custom fonts, you can define them here as well:
  # fonts:
  #   - family: JosefinSans_Bold
  #     fonts:
  #       - asset: assets/fonts/JosefinSans-Bold.ttf

